(in-package :yashmup)

(defun main ()
  (setf *running* t)
  (sdl:with-init (sdl:sdl-init-video sdl:sdl-init-audio)
    (sdl:initialise-default-font)
    (sdl:window *screen-width* *screen-height*
		:title-caption "PEW PEW"
		:icon-caption "PEW PEW")
    (setf (sdl:frame-rate) 60)
    (sdl:clear-display *bg-color*)
    (init-resources)
    (play-game)))

(defun play-game ()
  (let ((player-ship (make-instance 'player-ship))
	(enemy (make-instance 'enemy))
	(bg (make-instance 'background)))
    (sdl:with-events ()
      (:quit-event () (prog1 t
			(setf *running* nil)
			(format t "Total enemy damage: ~a" (damage enemy))
			(clrhash *keys-held-down*)
			(setf *projectiles* nil)))
      (:key-down-event (:key key)
		       (handle-key-down key))
      (:key-up-event (:key key)
		     (handle-key-up key))
      (:idle ()
	     (update bg)
	     (draw bg)
	     (mapc #'update *projectiles*)
	     (update player-ship)
	     (update enemy)
	     (draw enemy)
	     (draw player-ship)
	     (mapc #'draw *projectiles*)
	     (mapc (lambda (pew)
	     	     (when (collided-p enemy pew)
	     	       (incf (damage enemy))
	     	       (setf *projectiles* (delete pew *projectiles*))))
	     	   *projectiles*)
	     (sdl:update-display)
	     (when (not *running*)
	       (sdl:push-quit-event))))))
