;; level-script file for testing 
(in-package :yashmup)
(dotimes (ix 20)
  (let ((an-enemy (make-instance 'enemy)))
    (fork (:delay 60)
      (setf (angle an-enemy) 180)
      (setf (velocity an-enemy) 1)
      (fire! an-enemy)
      (fork (:delay 120)
	(setf (angle an-enemy) 0)
	(setf (velocity an-enemy) 3)
	(fork (:delay 10 :repeat 3)
	  (fire! an-enemy))))
    (push an-enemy (enemies *game*))))

(dotimes (ix 20)
  (let ((an-enemy (make-instance 'enemy)))
    (fork (:delay 60)
      (setf (angle an-enemy) 180)
      (setf (velocity an-enemy) 1)
      (fire! an-enemy)
      (fork (:delay 120)
	(setf (angle an-enemy) 0)
	(setf (velocity an-enemy) 3)
	(fork (:delay 10 :repeat 3)
	  (fire! an-enemy))))
    (attach an-enemy *game*)))

(defun move-in-curve (obj &optional (delta-theta 1))
  (dotimes (i 600)
    (fork (:delay i)
      (incf (angle obj) delta-theta)))
  (fork (:delay 600)
    (detach obj *game*)))

(defun move-in-rose (obj &optional (k 5))
  (with-slots ((theta angle)
	       (radius velocity)) obj
   (let ((initial-radius radius))
     (dotimes (i 600)
       (fork (:delay (* i))
	 (incf theta)
	 (setf radius (* initial-radius (cos (* k (degrees-to-radians theta)))))))))
  (fork (:delay 600)
    (detach obj *game*)))
